apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: course
        - name: description
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: description
        - name: owner
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: owner